.PHONY: v1 v2 v3

v1: v1/OrbOfSatisfaction.t
	t3make -FC -Fs v1 -d -f OrbOfSatisfaction

v2: v2/OrbOfSatisfaction.t
	t3make -FC -Fs v2 -d -f OrbOfSatisfaction

v3: v3/OrbOfSatisfaction.t
	t3make -FC -Fs v3 -d -f OrbOfSatisfaction

clean:
	rm -r obj
	rm OrbOfSatisfaction.t3


